name: Generate Galeri JSON (WEBP Only)

on:
  push:
    paths:
      - 'galeri/**'

jobs:
  generate-json-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate data-galeri.json dari .webp
        run: |
          echo "{" > data-galeri.json
          for folder in galeri/*/ ; do
            keg=$(basename "$folder")
            echo "  \"$keg\": [" >> data-galeri.json
            find "$folder" -type f -iname "*.webp" | sed 's|.*/||' | awk '{ print "    \"" $0 "\"," }' >> data-galeri.json
            sed -i '$ s/,$//' data-galeri.json
            echo "  ]," >> data-galeri.json
          done
          sed -i '$ s/},/}/' data-galeri.json
          echo "}" >> data-galeri.json

      - name: Commit perubahan JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data-galeri.json
          git commit -m "Update otomatis data-galeri.json dari file .webp"
          git push
